### ISSUE TITLE
ccl.c does not compile

### ISSUE THREAD

**Issue by kschwi** [ejbergdk/loconet-avrda#6]
CCL_SEQSEL_DISABLE_gc is not more a part of the avr128da48.h. CCL_SEQSEL0|1|2_DISABLE_gc are currently in the system include. I used mplabx v5.45 which provides the respective header files.

**Comment by ejbergdk** [comment]
I'm sorry to hear that. I have no problem compiling with Atmel (Microchip) Studio 7.
I don't know mplabx, but does it have "device family packs" to provide support for processor families? If so, have you tried updating the pack for AVR-Dx?

**Comment by kschwi** [comment]
Using Linux as OS mplabx provides the include files for all AVR-Dx CPUs. As a compiler I use my "old" avr-gcc 7.3.0 which compiles and links fine. Either Microchip changed the  CCL_SEQSEL_DISABLE_gc generally from the global name to the specialized named or it is still an inconsistency between mplabx and Studio 7. Which version of Studio 7 do you use? In a VM  I use Studio 7.0.132 and there is no Dx support :-(
BTW: I downloaded Studio 7 too, but it does not contain any AVR-Dx parts.

**Comment by ejbergdk** [comment]
> Either Microchip changed the CCL_SEQSEL_DISABLE_gc generally from the global name to the specialized named or it is still an inconsistency between mplabx and Studio 7.

I looked into it some more, and they did indeed change it, but the other way. They went from the specialized names to the generic in device pack version 1.6.76. They even put it in the change note:
> Removed numbering on SEQSEL bitfield name in CCL.SEQCTRLn registers, which results in shared bitfield description for SEQSEL bitfields. Updated various CCL captions.

I use Studio 7.0.2397, and has added AVR-Dx support by installing the appropriate device pack.

It seems MPLAB X also use device packs, so it should just be a matter of installing the latest one for AVR-Dx:
[https://microchipdeveloper.com/mplabx:projects-packs#toc2](https://microchipdeveloper.com/mplabx:projects-packs#toc2)

**Comment by kschwi** [comment]
This issue can be closed. With the pack update it compiles. mplabx distributes the pack-extensions somewhere in your home directory. This leads to different include-path for every new pack installation. "Brilliant solution"...
